[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FLUNED-repository"
dynamic     = ["version"]
description = "Tool to simulate irradiated coolant in fusion installations"
authors = [
  { name = "Marco De Pietri", email = "mdepietri@ind.uned.es" }
]
requires-python = ">=3.13,<3.14"

dependencies = [
  "h5py>=3.15,<4.0",
  "numpy>=2.4,<3.0",
  "vtk>=9.5,<10.0",
  "pyvista>=0.47,<0.48",
  "meshio[all]>=5.3,<6.0",
  "iapws>=1.5",
  "lxml>=6.0,<7.0",
  "tqdm>=4.67,<5.0",
]

[project.optional-dependencies]
docs = [
  "sphinx>=7.3",
  "sphinx-copybutton",
  "sphinx-rtd-theme",
  "furo",
  "myst-parser",
]

[project.scripts]
fluned-post = "fluned.fluned_post:main"
fluned-post-multi-isotopes = "fluned.fluned_post_multi_isotopes:main"
fluned = "fluned.fluned:main"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"isotopes" = ["isotopes.json"]

[tool.setuptools.dynamic]
version     = { attr = "fluned.__version__" }
