name: Build & Deploy Docs
on:
  push:
    branches: [ main , multi-isotope-1]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: pip install sphinx sphinx-rtd-theme
      - name: Build HTML
        run: sphinx-build -b html docs/source build/html
      - uses: actions/upload-pages-artifact@v3
        with: { path: build/html }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: { id-token: write, pages: write }
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4

