name: Build & Deploy Docs
on:
  push:
    branches: [ main , multi-isotope-1]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with: { python-version: '3.13' }
      - name: Install docs deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            latexmk \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            fonts-freefont-otf
          pip install ".[docs]"
      - name: Build docs
        run: |
          sphinx-build -M latexpdf docs/source build
          sphinx-build -M html docs/source build
          mkdir -p build/html/_downloads
          cp build/latex/FLUNED.pdf build/html/_downloads/FLUNED.pdf
      - uses: actions/upload-pages-artifact@v5
        with: { path: build/html }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: { id-token: write, pages: write }
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - id: deployment
      uses: actions/deploy-pages@v5
